print("WORKING NUMBERS: 201, 634, 241, 124")
entry = int(input("Enter a pokedex entry: "))

if entry == 201:
  print("MMMMMMMMMMWNK0OOO0XWMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMWXOxolcc:;;:odONMMMMMMMMMMMMMMMMM")
  print("MMMMMMXOdodkO00Oxl:,,,l0WMMMMMMMMMMMMMMM")
  print("MMMMWKxodOXWWWWNX0o:;;,:0MMMMMMMMMMMMMMM")
  print("MMMMXdcdKWNKO0NXKKOl;;;,lkkOOOOOO000NMMM")
  print("MMMWOlckNWKdcxKKKKOl;;;,,:::::;;;:;;OMMM")
  print("MMMMOc:xKXX0OKXXXKx:;;,,;dOKKKOo;,:kNMMM")
  print("MMMMXd:ckKXXXXNNKxc;;'';:;cdOOo;,lKWMMMM")
  print("MMMMMXd:cok0KK0ko:,'',dKKxl;,'':kNMMMMMM")
  print("MMMMMMNOo:::cc:;,,:dkKWMMMWKxoxKWMMMMMMM")
  print("MMMMMMMMNKxc;,;oxO0KXNMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMM0c;,cxxo;''lKMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMNx:,,,,,;;cokNMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMKl;'cOO0KXWMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMNk:,,kWMMMMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMWNKxc:,:0MMMMMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMXkdl:;,;;:lk0NMMMMMMMMMMMMMMMMMMMMMMM")
  print("MMW0l::coddc;;;,oNMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMWNKXNMMMNOdlcxNMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMM")
  print("Unown appears in, Gold, Silver, Crystal, Stadium 2, Ruby, Sapphire, Emerald, FireRed, LeafGreen, Diamond, Pearl, Platinum, HeartGold, SoulSilver, Black, White, Black 2, White 2, X, Y, Omega Ruby, Alpha Sapphire, Brilliant Diamond, Shining Pearl, Legends: Arceus, Smash Bros Melee in a pokeball, and Smash Bros Ultimate as a spirit.")

if entry == 634:
  print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMWK0WMMMMMMMWXKNMMMMMMWN0ONMMMMMMMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMWOokNMMMMWKkdkNMMMMMMWXxckWMMMMMWNXKNMMMMMMMMMMMMMMM")
  print("MMMMMMMMMXo:dXMW0dclkNMMMMMMMWNk;cOWMWKOxooONMMMMMMMMMMMMMMM")
  print("MMMMMMMMMWO:,lkd::o0WMMMMMMMMMWO:,lOOoc:cdKWMMMMMMMMMMMMMMMM")
  print("MMMMMMNKOkdc;;;;:xXMMMMMMMWXK00kc,;;;:lx0NMMMMMMMMMMMMMMMMMM")
  print("MMMMW0oc:::::::::lxXWMMMWKxlc:::::;;:xXWMMMMMMMMMMMMMMMMMMMM")
  print("MMMWOc;:::;;:::::::l0WMXxc:;:::::::::l0WMMMMMMMMMMMMMMMMMMMM")
  print("MMM0c,,;,,,,;;;,;:::l0Ko;;,,;;;;::;:c:l0MMMMMMMMMMMMMMMMMMMM")
  print("MMM0c:::c:;,,;;;;;;,:kd,',,,,,,,,,,;::;dNMMMMMMMMMMMMMMMMMMM")
  print("MMMWKxoodl;;;;,,,,,,lK0c,:c:;;:::;,,,,,oXMMMMMMMMMMMMMMMMMMM")
  print("MMMMWNXKXkc:::;;,',;xWWKo::ccclcc:;;,,c0WMMMMMMMMWWXK0OOXWMM")
  print("MMMMMMMNOoccc:;;,,,;dOXW0c,;;:::;;;,:xXWMMWNX0Okxolc::;ckNMM")
  print("MMMX00KK0dlc:;,,,,,,;dK0dc,,,,,,,,,cOWMNOdlc:;,,,,,;:lx0NMMM")
  print("MMN0o;;;:ccc;,;;;;;;ckW0c;;;;,,,;,;lxkxc,,,,,,,;cldkKNWMMMMM")
  print("MMNOxl:,,'',,;;:::::cOWNx::::::::;;::;,,;:loxkOKNWMMMMMMMMMM")
  print("MMMMWNXKOxdolc:::::::lxko:::::::;,,,,:dOKXNWMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMMMWNKx:;::::;,,,;::::::;;;;;dNMMMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMMMMXkl;;:::::;,,;:::::;;::::cdOXMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMMMNOc,,,;;:;;;,,;;;:;;,,;;::;:xNMMMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMWKd:,,,,,,,,,,,,,,,,,,,,,,,,,;lONWMMMMMMMMMMMMMMMMM")
  print("MMMMMMMMMWXkc;,,,,,,,,,,,,,,,,,,,,,,,,,;:lxKWMMMMMMMMMMMMMMM")
  print("MMMMMMMMMNOoc;,,,,,,,,,,,,,,,,,,,,,,,',:c:;:d0NMMMMMMMMMMMMM")
  print("MMMMMMMW0xooc;,''',,,,,,,,,,,,,,,,,,',:lool:;:oKWMMMMMMMMMMM")
  print("MMMMMMWOcclc::;,'',,,,,,,,,,,,,''','',clloooc;;lKMMMMMMMMMMM")
  print("MMMMMWOc;;:::c:;,,',,;:;;,;;;;,,',,:llc::clcc;,;lkKWMMMMMMMM")
  print("MMMWN0dc::clx0kxxxxO0OOkxxdxxxxxxO0XWN0d:::;:;:oxkKWMMMMMMMM")
  print("MMMWNNXKK00KNMMMMMMMMMMMMMMMMMMMMMMMMWNOdllllokXWMMMMMMMMMMM")
  print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNNNWMMMMMMMMMMM")
  print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
  print("Zweilous appears in Black, White, Black 2, White 2, X, Y, Omega Ruby, Alpha Sapphire, Sword, and Shield.")

if entry == 241:
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@#BBB#&@@B7&@@@@P#@&BB@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@&Y!!JP#G7YBGBP:~#&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@&&BB##J^:!7J?PG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@###!: ~B?:!7:B@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@#B#P::.!G7...:7Y77@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@&&#B@&@&###Y.::..^^::::^:^@@@#&#&@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@#BBP::^75#P.....!5Y555?7JY7!!7Y@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@Y:......^YP?~:.^77?Y?77!~!!!~J@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@5:.::::..~B#BPYY5PG#G?!!!!~5@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@&7:.:....~7JPB###&##G^~!!G@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@#^:^^^^:...::^~!77^:..:^!5#@B?#@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@!::^^~:..........:.^.    .~..G@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@Y...........:.  :^.^.   ....:G&&@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@&?..::::...:: ................~^!5&@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@P.::.:::^^~........^::^.....::.::^B&@&@@@@@@@")
  print("@@@@@@@@@@@@@@@#:^.....::::^......^:^:     ..~:.J#B##@@@@@@@")
  print("@@@@@@@@@@@@@@@@G:::^Y7P5~.:^:    ...        ^^:P#BB@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@:..^B###B::^7:.............^7~~J&&@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@Y^^^7GBB5~~~7!^^^^:::::^^^^7!7G@@@@@@@@@@@@")
  print("@@@@@@@@@##&@@@@@@7~!~!!!~!!~7!^^^^^^^^^^~JGB&@@@@@@@@@@@@@@")
  print("@@@@@@@@BGG#B&@@@@@Y~~~~!!!!!?7!~~^^^~!JG&@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@&#P7B@@@@@@@&PJ7!!7JY77?Y5PG#&@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@#?5&@@@@@@@@@@@@@P?5&@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@BY5GB#&&@@@&#PY5#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@&#BGPPGBB#&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  

if entry == 124:
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&#&@@@@@&#&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#7.  :^??:.   .^Y&@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@P:   .^:. :~~:     .?@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@B:   .7JJJ!?YYYJ7.     .P@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@J    ^5YYYJJ??7777J^  ..  ?@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@! .  :P^ .?777^ .!!7J: .:.  7@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@J :. .YJ^.~7~!?!..!777J.  :  .7@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@B ..  7?7???^?^~J77777JP~  .:.:^Y@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@:.:  .Y????7^7^:J??JY55P7   ~::~^#@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@B.:.  :5YJJY5?~!YYJ?JY5PP7   :::^~?@@@@@@@@&B@@@@@@@@@")
  print("@@@@@@@@@@&@@@@@@@@@@P:^   :5J?7~!Y5J~^^~!~~!5~   ^:^^!^@@&@@@@&YY@@#&@@@@@")
  print("@@@@@&&@@#?P@@@@@@@@@P~~...:5J???~...^!!7???77... ^:~^7~&#7Y&@&YB@BYY&@@@@@")
  print("@@@@@B55#@PY#@@B5Y&@@B~~~:::JYJJJJ..^J?JJJJJJ!::::~:~^?7&@@55P55P5G&@@@@@@@")
  print("@@@@@@@#555555YP##&&@@7~!^::~5YYJ!^^^7YYYYY57::::~^^~~Y7P#@GY55YYYPBGP5@@@@")
  print("@@@@PGGG5YYP5Y5?!^:::^^!^~^^:7Y??YYYJJ???JJ7::::~^:!:!:...::!JPPGPY&@@@@@@@")
  print("@@@@@&BGPGGB#B7:::^^:.:P5!?!~.7555YYYPYYY7:.^^~?^^~:~^.:::..7#@@@@#Y&@@@@@@")
  print("@@@@@&&@@@@@@@@&J^..:J&@@BYYYJ^!5JJJYPY?^^!7?YY^~~~!J:...^?#@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@&&@@@#5??????JY??7J5Y?J5YY557YY?P?YPBGB&@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@#PJJ7!7????Y?7??5YYYYYYYYYYYYYY5@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@#PJ??J7!!7?7?Y?!77J5YYYYYYYJYYJYYYYY#@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@&B5YJ!!7????J7!!7?5YYYYYYYYJ?J?Y5YYYJY#@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@&#BPYJJ?7!!!7?J?!!!!755Y555YYYJ?????Y5Y5B##&@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@&PJ?77??????777777!!!!!!Y5555555YYY??????J5YYGB&@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@P??JJJJJ?77??J?7!!!!!!!!!JPYYYYY55YYJ???????JJYYYY5G#@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@&BPYJ5?77777777??JPPGGPP5YYYJ???777JYYYJJJYPB&@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@&&#BGGPPGGGB#&@@@@@@@#G5YJJY5B&@@@@&&&@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
  print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")